public class NumberConstants {
   public static final Double MIN_DOUBLE_VALUE = double.valueOf('-9.223372e+18');
   public static final Double MAX_DOUBLE_VALUE = double.valueOf('9.223372e+18');
   public static final Integer MIN_INTEGER_VALUE = Integer.valueOf('-2147483648');
   public static final Integer MAX_INTEGER_VALUE = Integer.valueOf('2147483647');
   public static final Long MIN_LONG_VALUE = Long.valueOf('-999999999999999999');
   public static final Long MAX_LONG_VALUE = Long.valueOf('999999999999999999');
}